import type { Item } from "./schema";

// Phase 0 mock data. ~10 plausible SKUs to drive the demo build.
// Expand to 30-40 once the page layouts are real.
export const MOCK_ITEMS: Item[] = [
  {
    slug: "okra",
    name: "Okra (Ladies' Finger)",
    category: "vegetables",
    stock: "In Stock",
    price: 4.5,
    unit: "kg",
    origin: "India",
    featured: true,
  },
  {
    slug: "snake-gourd",
    name: "Snake Gourd",
    category: "vegetables",
    stock: "Low",
    price: 3.8,
    unit: "kg",
    origin: "Sri Lanka",
    featured: false,
  },
  {
    slug: "curry-leaves",
    name: "Fresh Curry Leaves",
    category: "vegetables",
    stock: "In Stock",
    price: 1.5,
    unit: "bunch",
    origin: "India",
    featured: true,
  },
  {
    slug: "alphonso-mango",
    name: "Alphonso Mango",
    category: "fruits",
    stock: "In Stock",
    price: 12.0,
    unit: "kg",
    origin: "Alphonso, India",
    featured: true,
  },
  {
    slug: "young-coconut",
    name: "Young Coconut",
    category: "fruits",
    stock: "In Stock",
    price: 3.5,
    unit: "piece",
    origin: "Thailand",
    featured: false,
  },
  {
    slug: "seer-fish",
    name: "Seer Fish (Vanjaram)",
    category: "fish",
    stock: "Low",
    price: 22.0,
    unit: "kg",
    origin: "Indian Ocean",
    featured: true,
  },
  {
    slug: "tilapia",
    name: "Tilapia",
    category: "fish",
    stock: "Out of Stock",
    price: 9.5,
    unit: "kg",
    origin: "Farmed",
    featured: false,
  },
  {
    slug: "goat-curry-cut",
    name: "Goat Curry Cut",
    category: "meat",
    stock: "In Stock",
    price: 16.0,
    unit: "kg",
    origin: "Germany",
    featured: true,
  },
  {
    slug: "basmati-rice-5kg",
    name: "Basmati Rice (Premium)",
    category: "dry-goods",
    stock: "In Stock",
    price: 14.5,
    unit: "5kg",
    origin: "India",
    featured: true,
  },
  {
    slug: "toor-dal",
    name: "Toor Dal",
    category: "dry-goods",
    stock: "In Stock",
    price: 3.2,
    unit: "kg",
    origin: "India",
    featured: false,
  },
];
